set(0,'DefaultTextFontsize',15, ...    
        'DefaultFigureWindowStyle','docked', ...
        'DefaultFigureColor',[1 1 1],...
    'defaulttextinterpreter','latex',...
    'DefaultTextFontWeight','normal', ...
    'DefaultAxesFontsize',15, ...
    'DefaultAxesFontname','Arial', ...
    'DefaultLineLineWidth', 1)

%% 
A = userpath;
A=A(1:end);
addpath(genpath(A))


A=A(1:end-1);
C= strsplit(A,'/');
C=C(1:end);
addpath('/Applications/Fiji.app/scripts');

clear all