hFit = findobj(gcf, 'type', 'line');
hE = findobj(gcf, 'type', 'errorbar');

set(0,'ShowhiddenHandles','on')

%hTitle  = findobj(gcf, 'tag', 'title');
hTitle  = get(gca, 'title');
hXLabel = findobj(gcf, 'type', 'xlabel');
hYLabel = findobj(gcf, 'type', 'ylabel');
%hXLabel = get(gca, 'xlabel');
%hYLabel = get(gca, 'ylabel');

hText    = findobj(gcf, 'type', 'text');
hLegend = findobj(gcf, 'tag', 'legend');

%hLegend = get(gca, 'legend'); 

%hText = get(gca, 'text');

%set( gca                       , ...
%    'FontName'   , 'Helvetica' );
%set([hTitle, hXLabel, hYLabel, hText], ...
 %   'FontName'   , 'Helvetica');

set([hLegend, gca]             , ...
    'LineWidth' , 0.5           , ...
    'YColor' , [0.3 0.3 0.3]    ,...
    'XColor' , [0.3 0.3 0.3]    ,...
    'FontSize'   , 10);

set([hXLabel, hYLabel, hText]  , ...
    'FontSize'   , 14           ,...         
    'Color'     , [.3 .3 .3]  );

set( hTitle                    , ...
    'FontSize'   , 20          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );

set(gcf, 'PaperPositionMode', 'auto');